services:
    _defaults:
        autoconfigure: true

    2biased.conato.basics.event_listeners:
        namespace: TwoBiased\ContaoBasicsBundle\EventListener\
        resource: '../src/EventListener'

    TwoBiased\ContaoBasicsBundle\Controller\FrontendModule\BrandController:
        arguments:
            - '@contao.routing.content_url_generator'
            - '@contao.image.studio'

    TwoBiased\ContaoBasicsBundle\Controller\FrontendModule\ContainerController: ~
